### ISSUE TITLE
Prebuilt binaries

### ISSUE THREAD

**Issue by develar** [SirAlex/RemoteSignTool#1]
Could you please provide binaries?

**Comment by develar** [comment]
I am going to use it for https://github.com/electron-userland/electron-builder/issues/1299

**Comment by SirAlex** [comment]
Ok, will prepare binaries today.

**Comment by SirAlex** [comment]
Sorry for delay, binaries available at releases page
https://github.com/SirAlex/RemoteSignTool/releases
