### ISSUE TITLE
AutoPin sometimes fails, and solution to it

### ISSUE THREAD

**Issue by robiwano** [SirAlex/RemoteSignTool#4]
I've had several instances where the remote signing fails because AutoPin fails. When logging in with TeamViewer to see why the signing failed I see an open "Token Logon" dialog without anything entered in the password field.

So I tried using AutoIt instead (https://www.autoitscript.com/site/), with the following script compiled to an x64 executable: 

```
$Caption = "Token Logon"
$Pwd = "<token password here>"

While 1
    Local $hWnd = WinWaitActive($Caption)
    ControlSetText($hWnd, "", "Edit2", $Pwd)
    Sleep(500)
    ControlClick($hWnd, "", "Button1")
    WinWaitClose($Caption)
Wend

```

and that works like a charm in conjunction with the signtool server.

**Comment by SirAlex** [comment]
Thanks! We also encountered same problems with AutoPin. We will try your solution.

**Comment by SirAlex** [comment]
Added your script with little modifications (for compatibility with old AutoPin.exe). Again, Thank You!

**Comment by robiwano** [comment]
I noticed that with that script, autoit fails to enter the password sometimes because the Token Logon dialog pops up, but inactive. This update fixes that:
```
$Caption = "Token Logon"

While 1
    Local $hWnd = WinWait($Caption)
    WinActivate($hWnd)
    ControlSetText($hWnd, "", "Edit2", $CmdLine[1])
    Sleep(500)
    ControlClick($hWnd, "", "Button1")
    WinWaitClose($Caption)
Wend

```

**Comment by robiwano** [comment]
@SirAlex ping, just wanted you to see the improvements above :)
