### ISSUE TITLE
Autostart signing server

### ISSUE THREAD

**Issue by robiwano** [SirAlex/RemoteSignTool#5]
I'd like to be able to start the server without having to click the "Test and Start" button, is this possible, perhaps through a cmd line option ?

**Comment by apderosso** [comment]
Yes, this would be a nice feature

**Comment by SirAlex** [comment]
Added -autostart cmd line switch in v1.1.0.1

Thank you for suggestion!

**Comment by robiwano** [comment]
@SirAlex A question: Will the server retry several times before giving up ? I'm thinking of setting up a server that autostarts Autopwd "service" and server on a reboot, and I want to check if there is a failure possibility (if server tests to start before autopwd is "active")

**Comment by apderosso** [comment]
@robiwano I was able to get the RemoteSignTool and AutoPin to start on server reboot. I haven't had any issues with the password service not running in time for the sign server to start up correctly. I use a simple batch script that runs on system startup:

```
Taskkill /IM AutoPin.exe /F
start AutoPin.exe "[signing password]"
start RemoteSignTool_Server.exe -autostart
```

**Comment by robiwano** [comment]
Ok, you did this with autologin (and the script in "Start" folder) ?

**Comment by robiwano** [comment]
Alrite, I've setup autologin and shortcuts to the autopin and server exe, and it seem to work just fine :)

**Comment by apderosso** [comment]
Yessir, the user on our machine uses autologin and then runs that script to start the signing server.
